# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_lcn_scanner', [dirname(__file__)])
        except ImportError:
            import _lcn_scanner
            return _lcn_scanner
        if fp is not None:
            try:
                _mod = imp.load_module('_lcn_scanner', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _lcn_scanner = swig_import_helper()
    del swig_import_helper
else:
    import _lcn_scanner
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class lcn_entry(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, lcn_entry, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, lcn_entry, name)
    __repr__ = _swig_repr
    __swig_setmethods__["nid"] = _lcn_scanner.lcn_entry_nid_set
    __swig_getmethods__["nid"] = _lcn_scanner.lcn_entry_nid_get
    if _newclass:nid = _swig_property(_lcn_scanner.lcn_entry_nid_get, _lcn_scanner.lcn_entry_nid_set)
    __swig_setmethods__["tsid"] = _lcn_scanner.lcn_entry_tsid_set
    __swig_getmethods__["tsid"] = _lcn_scanner.lcn_entry_tsid_get
    if _newclass:tsid = _swig_property(_lcn_scanner.lcn_entry_tsid_get, _lcn_scanner.lcn_entry_tsid_set)
    __swig_setmethods__["sid"] = _lcn_scanner.lcn_entry_sid_set
    __swig_getmethods__["sid"] = _lcn_scanner.lcn_entry_sid_get
    if _newclass:sid = _swig_property(_lcn_scanner.lcn_entry_sid_get, _lcn_scanner.lcn_entry_sid_set)
    __swig_setmethods__["lcn"] = _lcn_scanner.lcn_entry_lcn_set
    __swig_getmethods__["lcn"] = _lcn_scanner.lcn_entry_lcn_get
    if _newclass:lcn = _swig_property(_lcn_scanner.lcn_entry_lcn_get, _lcn_scanner.lcn_entry_lcn_set)
    __swig_setmethods__["next"] = _lcn_scanner.lcn_entry_next_set
    __swig_getmethods__["next"] = _lcn_scanner.lcn_entry_next_get
    if _newclass:next = _swig_property(_lcn_scanner.lcn_entry_next_get, _lcn_scanner.lcn_entry_next_set)
    def __init__(self): 
        this = _lcn_scanner.new_lcn_entry()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _lcn_scanner.delete_lcn_entry
    __del__ = lambda self : None;
lcn_entry_swigregister = _lcn_scanner.lcn_entry_swigregister
lcn_entry_swigregister(lcn_entry)


def demuxer_open():
  return _lcn_scanner.demuxer_open()
demuxer_open = _lcn_scanner.demuxer_open

def demuxer_close():
  return _lcn_scanner.demuxer_close()
demuxer_close = _lcn_scanner.demuxer_close

def get_lcn():
  return _lcn_scanner.get_lcn()
get_lcn = _lcn_scanner.get_lcn

def lcn_entry_clean(*args):
  return _lcn_scanner.lcn_entry_clean(*args)
lcn_entry_clean = _lcn_scanner.lcn_entry_clean


